_target_: lerobot.common.robot_devices.robots.manipulator.ManipulatorRobot
robot_type: so100
calibration_dir: .cache/calibration/so100_plus


max_relative_target: null

controllers:
  right:
    _target_: lerobot.common.robot_devices.controllers.joycon_controller_distance.JoyConController_plus
    name: right
    
follower_arms:
  right:
    _target_: lerobot.common.robot_devices.motors.feetech.FeetechMotorsBus
    port: /dev/ttyACM0
    motors:
      # name: (index, model)
      shoulder_rotation_joint: [1, "sts3215"]
      shoulder_pitch_joint: [2, "sts3215"]
      ellbow_joint: [3, "sts3215"]
      wrist_pitch_joint: [4, "sts3215"]
      wrist_jaw_joint: [5, "sts3215"]
      wrist_roll_joint: [6, "sts3215"]
      gripper_joint: [7, "sts3215"]

cameras:
  webcam:
    _target_: lerobot.common.robot_devices.cameras.opencv.OpenCVCamera
    camera_index: 2
    fps: 30
    width: 640
    height: 480
  phone:
    _target_: lerobot.common.robot_devices.cameras.opencv.OpenCVCamera
    camera_index: 1
    fps: 30
    width: 640
    height: 480