# @package _global_

fps: 15

env:
  name: xarm
  task: XarmLift-v0
  image_size: 84
  state_dim: 4
  action_dim: 4
  fps: ${fps}
  episode_length: 200
  gym:
    obs_type: pixels_agent_pos
    render_mode: rgb_array
    visualization_width: 384
    visualization_height: 384
